name: Build Package

on: workflow_call

jobs:
  build:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: |
          python -m pip install uv
      - name: Install build and twine
        run: |
          uv pip install --system build twine
      - name: Run build
        run: python -m build
      - name: Run twine check
        run: twine check --strict dist/*
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.tar.gz
