name: Unit Tests (py312)
# Test also with Python 3.12 (experimental; workflow will not fail on error.)

on: workflow_call

jobs:
  test313:
    name: Test on ${{matrix.python.toxenv}}-${{matrix.platform.toxenv}} (experimental)
    continue-on-error: true
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            toxenv: linux
          - runner: windows-latest
            toxenv: windows
        python:
          - version: '3.13.0-alpha - 3.13.0'
            toxenv: 'py313'
    steps:
      - uses: actions/checkout@v4
      - name: Install Python ${{ matrix.python.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
      - name: Install tox
        run: python -m pip install tox-uv
      - name: Run pytest
        run: tox -e ${{matrix.python.toxenv}}-${{matrix.platform.toxenv}}
