name: Build and publish package

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 1
          lfs: true
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # cache pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt
      - name: Print debugging information
        run: |
          echo "github.ref:" ${{github.ref}}
          echo "github.event_name:" ${{github.event_name}}
          echo "github.head_ref:" ${{github.head_ref}}
          echo "github.base_ref:" ${{github.base_ref}}
          set -x
          git rev-parse --abbrev-ref HEAD
          git branch
          git branch -a
          git remote -v
          python -V
          pip list --not-required
          pip list
      - name: Install build
        run: pip install build
      - name: Build Python package
        run: python -m build

  publish:
    needs: build
    name: Publish package
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # cache pip dependencies
      - name: Install twine
        run: pip install twine
      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: python -m twine upload --repository pypi dist/*
