# https://github.com/ymyzk/tox-gh-actions

name: tox

on: [push, pull_request]

jobs:
  tox:
    name: tox
    runs-on: ${{ matrix.platform }}
    continue-on-error: true
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # cache pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install tox tox-gh-actions
      - name: Run tox
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}
